#!/bin/bash

echo "🚀 Setting up Resend Email Service"
echo ""
echo "Step 1: Create Account"
echo "→ Go to: https://resend.com/signup"
echo "→ Sign up with your email (FREE - no credit card needed)"
echo ""
echo "Step 2: Get API Key"
echo "→ After signup, go to: https://resend.com/api-keys"
echo "→ Click 'Create API Key'"
echo "→ Name it: 'TaskWebsite Production'"
echo "→ Copy the key (starts with 're_')"
echo ""
echo "Step 3: Add to Vercel"
echo "→ Go to: https://vercel.com/vladicavram/taskwebsite/settings/environment-variables"
echo "→ Add variable:"
echo "   Name: RESEND_API_KEY"
echo "   Value: [paste your API key]"
echo "→ Click 'Save'"
echo ""
echo "Step 4: Test"
echo "→ Visit: https://dozo.md/forgot-password"
echo "→ Enter an email and submit"
echo "→ Check your inbox for password reset email!"
echo ""
echo "✅ Free tier includes 100 emails/day - perfect for your site!"
